import {
  CalyxApiError,
  createCalyxConversation,
  getCalyxConversation,
  sendCalyxTurn,
  type BrainMission,
} from '@/lib/calyxWorkspace';
import { calyxContextPacket, readCalyxSessionContext } from '@/features/calyx-workspace/sessionContext';

export interface CalyxRequest {
  concept: string;
  question: string;
  context?: Record<string, unknown>;
  surface?: string;
  module?: string;
  project_id?: string;
}

export interface CalyxCitation { label: string; detail?: string; }

export interface CalyxResponse {
  concept: string;
  question: string;
  concise_answer: string;
  expanded_explanation?: string;
  developmental_mechanism?: string;
  anatomy?: string;
  physiology?: string;
  ecological_significance?: string;
  evolutionary_context?: string;
  identification_significance?: string;
  evidence?: string;
  uncertainty?: string;
  related_concepts?: string[];
  related_taxa?: string[];
  related_images?: string[];
  follow_up_questions?: string[];
  citations?: CalyxCitation[];
  confidence_or_review_state?: string;
  mission?: BrainMission | null;
  provider?: string;
  provider_model?: string;
}

export const CALYX_ENDPOINT = '/api/calyx/speak/conversations';
export const CALYX_DEMO_LABEL = 'Live governed Calyx conversation';
export const CALYX_DISCLOSURE = 'Calyx replies are generated by the server-owned Orchid Continuum conversation service. Scientific turns may invoke governed Brain missions; provider memory is not scientific evidence and no answer is automatically published.';

const SESSION_THREAD_KEY = 'oc-calyx-adaptive-session-thread:v2';
const DEFAULT_PROJECT = 'orchid-continuum-adaptive-workspace';

async function conversationForSession(): Promise<string> {
  if (typeof window !== 'undefined') {
    const existing = window.sessionStorage.getItem(SESSION_THREAD_KEY);
    if (existing) {
      try {
        await getCalyxConversation(existing);
        return existing;
      } catch (error) {
        if (!(error instanceof CalyxApiError) || error.kind !== 'route_unavailable') {
          window.sessionStorage.removeItem(SESSION_THREAD_KEY);
        }
      }
    }
  }
  const created = await createCalyxConversation({
    title: 'Orchid Continuum — adaptive Calyx session',
    project_id: DEFAULT_PROJECT,
    context: calyxContextPacket({
      surface: 'orchid-continuum-adaptive-workspace',
      scientific_write_authority: false,
      publication_authority: false,
    }),
  });
  if (typeof window !== 'undefined') window.sessionStorage.setItem(SESSION_THREAD_KEY, created.conversation_id);
  return created.conversation_id;
}

function citationsFromMission(mission: BrainMission | null): CalyxCitation[] {
  if (!mission) return [];
  return (mission.sources ?? []).slice(0, 10).map((source, index) => ({ label: source.title || `Source ${index + 1}`, detail: source.authorized_excerpt || undefined }));
}

function interactionContextText(concept: string, surface: string): string {
  const session = readCalyxSessionContext();
  const recent = session.trail
    .slice(-5)
    .map((item) => item.label ?? item.object_id ?? item.surface)
    .filter(Boolean)
    .join(' → ');
  return [
    `Current interface surface: ${surface}.`,
    `Current interface object or concept: ${concept}.`,
    recent ? `Recent interface trail: ${recent}.` : '',
    'Interface context is for conversational reference resolution only and is not scientific evidence.',
  ].filter(Boolean).join('\n');
}

export async function askCalyx(req: CalyxRequest): Promise<CalyxResponse> {
  const conversationId = await conversationForSession();
  const surface = req.surface?.trim() || 'illustrated-orchid-lexicon';
  const module = req.module?.trim() || surface;
  const projectId = req.project_id?.trim() || DEFAULT_PROJECT;
  const contextualQuestion = [
    interactionContextText(req.concept, surface),
    'Use canonical Orchid Continuum evidence and explicitly distinguish evidence, inference, missing evidence, and design suggestions.',
    req.question,
  ].join('\n');
  const turn = await sendCalyxTurn(conversationId, {
    message: contextualQuestion,
    project_id: projectId,
    context: calyxContextPacket({
      ...req.context,
      surface,
      module,
      concept: req.concept,
    }),
    research_mode: 'auto',
    retrieval_limit: 12,
  });
  const mission = turn.research?.mission ?? null;
  const uncertaintyParts: string[] = [];
  if (mission?.missing_evidence?.length) uncertaintyParts.push(`Evidence gaps: ${mission.missing_evidence.join('; ')}`);
  if (turn.research?.mission_error) uncertaintyParts.push(`Mission limitation: ${turn.research.mission_error}`);
  uncertaintyParts.push('This conversational reply is not automatically published knowledge.');
  return {
    concept: req.concept,
    question: req.question,
    concise_answer: turn.answer,
    uncertainty: uncertaintyParts.join(' '),
    citations: citationsFromMission(mission),
    confidence_or_review_state: mission ? `${mission.review_status || mission.state}${mission.confidence === null ? '' : ` · confidence ${mission.confidence.toFixed(2)}`}` : 'Conversational response; inspect governed evidence where available.',
    mission,
    provider: turn.provider?.name,
    provider_model: turn.provider?.model,
  };
}

export function calyxSuggestedQuestions(conceptLabel: string): string[] {
  return [
    `Why is ${conceptLabel} biologically important?`,
    `Show me how ${conceptLabel} connects to orchid identification characters.`,
    `What visual evidence would help me understand ${conceptLabel}?`,
    `What remains uncertain about ${conceptLabel}?`,
    `Tell me something surprising about ${conceptLabel}.`,
  ];
}

export const CALYX_DEMO_QUESTIONS = [
  'What is this structure or process?',
  'What evidence supports this explanation?',
  'What remains uncertain?',
  'How is this useful for orchid identification?',
  'How does this connect to Calyx Vision?',
];
