import {
  CalyxApiError,
  createCalyxConversation,
  getCalyxConversation,
  sendCalyxTurn,
  type BrainMission,
} from '@/lib/calyxWorkspace';

export interface CalyxRequest {
  concept: string;
  question: string;
  context?: Record<string, unknown>;
}

export interface CalyxCitation {
  label: string;
  detail?: string;
}

export interface CalyxResponse {
  concept: string;
  question: string;
  concise_answer: string;
  expanded_explanation?: string;
  anatomy?: string;
  physiology?: string;
  ecological_significance?: string;
  evolutionary_context?: string;
  identification_significance?: string;
  evidence?: string;
  uncertainty?: string;
  related_concepts?: string[];
  related_taxa?: string[];
  related_images?: string[];
  follow_up_questions?: string[];
  citations?: CalyxCitation[];
  confidence_or_review_state?: string;
  mission?: BrainMission | null;
  provider?: string;
  provider_model?: string;
}

export const CALYX_ENDPOINT = '/api/calyx/speak/conversations';
export const CALYX_DEMO_LABEL = 'Live governed Calyx conversation';
export const CALYX_DISCLOSURE =
  'Calyx replies are generated by the server-owned Orchid Continuum conversation service. Scientific turns may invoke governed Brain missions; provider memory is not scientific evidence and no answer is automatically published.';

const conversationKey = (concept: string) => `oc-lexicon-calyx-thread:${concept.toLocaleLowerCase()}`;

async function conversationForConcept(concept: string): Promise<string> {
  if (typeof window !== 'undefined') {
    const existing = window.localStorage.getItem(conversationKey(concept));
    if (existing) {
      try {
        await getCalyxConversation(existing);
        return existing;
      } catch (error) {
        if (!(error instanceof CalyxApiError) || error.kind !== 'route_unavailable') {
          window.localStorage.removeItem(conversationKey(concept));
        }
      }
    }
  }

  const created = await createCalyxConversation({
    title: `Illustrated Orchid Lexicon — ${concept}`,
    project_id: 'illustrated-orchid-lexicon',
    context: {
      surface: 'illustrated-orchid-lexicon',
      concept,
      scientific_write_authority: false,
      publication_authority: false,
    },
  });
  if (typeof window !== 'undefined') {
    window.localStorage.setItem(conversationKey(concept), created.conversation_id);
  }
  return created.conversation_id;
}

function citationsFromMission(mission: BrainMission | null): CalyxCitation[] {
  if (!mission) return [];
  return (mission.sources ?? []).slice(0, 10).map((source, index) => ({
    label: source.title || `Source ${index + 1}`,
    detail: source.authorized_excerpt || undefined,
  }));
}

export async function askCalyx(req: CalyxRequest): Promise<CalyxResponse> {
  const conversationId = await conversationForConcept(req.concept);
  const contextualQuestion = [
    `Current lexicon concept: ${req.concept}.`,
    'Use canonical Orchid Continuum evidence and explicitly distinguish evidence, inference, missing evidence, and design suggestions.',
    req.question,
  ].join('\n');

  const turn = await sendCalyxTurn(conversationId, {
    message: contextualQuestion,
    project_id: 'illustrated-orchid-lexicon',
    context: {
      ...req.context,
      surface: 'illustrated-orchid-lexicon',
      concept: req.concept,
    },
    research_mode: 'auto',
    retrieval_limit: 12,
  });

  const mission = turn.research?.mission ?? null;
  const uncertaintyParts: string[] = [];
  if (mission?.missing_evidence?.length) {
    uncertaintyParts.push(`Evidence gaps: ${mission.missing_evidence.join('; ')}`);
  }
  if (turn.research?.mission_error) uncertaintyParts.push(`Mission limitation: ${turn.research.mission_error}`);
  uncertaintyParts.push('This conversational reply is not automatically published knowledge.');

  return {
    concept: req.concept,
    question: req.question,
    concise_answer: turn.answer,
    uncertainty: uncertaintyParts.join(' '),
    citations: citationsFromMission(mission),
    confidence_or_review_state: mission
      ? `${mission.review_status || mission.state}${mission.confidence === null ? '' : ` · confidence ${mission.confidence.toFixed(2)}`}`
      : 'Conversational response; inspect Research details in Speak with Calyx for governed evidence.',
    mission,
    provider: turn.provider?.name,
    provider_model: turn.provider?.model,
  };
}

export const CALYX_DEMO_QUESTIONS = [
  'What is this structure or process?',
  'What evidence supports this explanation?',
  'What remains uncertain?',
  'How is this useful for orchid identification?',
  'How does this connect to Calyx Vision?',
];
