import {
  CalyxApiError,
  createCalyxConversation,
  getCalyxConversation,
  sendCalyxTurn,
  type BrainMission,
  type CalyxTurnResponse,
  type CalyxWorkspaceOutput,
} from '@/lib/calyxWorkspace';
import { calyxContextPacket, readCalyxSessionContext } from '@/features/calyx-workspace/sessionContext';
import { emitWorkspaceOutput, type WorkspaceOutput, type WorkspaceOutputPayload } from '@/features/calyx-workspace/workspaceOutputBus';

export interface CalyxRequest {
  concept: string;
  question: string;
  context?: Record<string, unknown>;
}

export interface CalyxCitation { label: string; detail?: string; }

export interface CalyxResponse {
  concept: string;
  question: string;
  concise_answer: string;
  expanded_explanation?: string;
  developmental_mechanism?: string;
  anatomy?: string;
  physiology?: string;
  ecological_significance?: string;
  evolutionary_context?: string;
  identification_significance?: string;
  evidence?: string;
  uncertainty?: string;
  related_concepts?: string[];
  related_taxa?: string[];
  related_images?: string[];
  follow_up_questions?: string[];
  citations?: CalyxCitation[];
  confidence_or_review_state?: string;
  mission?: BrainMission | null;
  provider?: string;
  provider_model?: string;
}

export const CALYX_ENDPOINT = '/api/calyx/speak/conversations';
export const CALYX_DEMO_LABEL = 'Live governed Calyx conversation';
export const CALYX_DISCLOSURE = 'Calyx replies are generated by the server-owned Orchid Continuum conversation service. Scientific turns may invoke governed Brain missions; provider memory is not scientific evidence and no answer is automatically published.';

const SESSION_THREAD_KEY = 'oc-lexicon-calyx-session-thread:v1';

async function conversationForSession(): Promise<string> {
  if (typeof window !== 'undefined') {
    const existing = window.sessionStorage.getItem(SESSION_THREAD_KEY);
    if (existing) {
      try {
        await getCalyxConversation(existing);
        return existing;
      } catch (error) {
        if (!(error instanceof CalyxApiError) || error.kind !== 'route_unavailable') {
          window.sessionStorage.removeItem(SESSION_THREAD_KEY);
        }
      }
    }
  }
  const created = await createCalyxConversation({
    title: 'Illustrated Orchid Lexicon — adaptive session',
    project_id: 'illustrated-orchid-lexicon',
    context: calyxContextPacket({
      surface: 'illustrated-orchid-lexicon',
      scientific_write_authority: false,
      publication_authority: false,
    }),
  });
  if (typeof window !== 'undefined') window.sessionStorage.setItem(SESSION_THREAD_KEY, created.conversation_id);
  return created.conversation_id;
}

function citationsFromMission(mission: BrainMission | null): CalyxCitation[] {
  if (!mission) return [];
  return (mission.sources ?? []).slice(0, 10).map((source, index) => ({ label: source.title || `Source ${index + 1}`, detail: source.authorized_excerpt || undefined }));
}

function interactionContextText(concept: string): string {
  const session = readCalyxSessionContext();
  const recent = session.trail
    .slice(-5)
    .map((item) => item.label ?? item.object_id ?? item.surface)
    .filter(Boolean)
    .join(' → ');
  return [
    `Current interface concept: ${concept}.`,
    recent ? `Recent interface trail: ${recent}.` : '',
    'Interface context is for conversational reference resolution only and is not scientific evidence.',
  ].filter(Boolean).join('\n');
}

function toWorkspaceOutput(serverOutput: CalyxWorkspaceOutput): WorkspaceOutput {
  return {
    id: serverOutput.id,
    kind: serverOutput.kind,
    title: serverOutput.title,
    subtitle: serverOutput.subtitle ?? undefined,
    provenance: {
      source_module: serverOutput.provenance.source_module,
      source_id: serverOutput.provenance.source_id ?? undefined,
      generated: serverOutput.provenance.generated,
      evidence_status: serverOutput.provenance.evidence_status,
    },
    payload: serverOutput.payload as WorkspaceOutputPayload,
    created_at: serverOutput.created_at,
  };
}

/**
 * Bridge from the server's grounded workspace_outputs (see backend
 * CALYX-MULTIMODAL-WORKSPACE-001) onto the existing workspaceOutputBus that
 * CalyxAdaptiveWorkspace already renders. Each output is validated
 * independently - one malformed or unexpectedly-shaped server output must
 * never break the turn itself or discard the outputs around it.
 */
function emitTurnWorkspaceOutputs(outputs: CalyxTurnResponse['workspace_outputs']): void {
  for (const serverOutput of outputs ?? []) {
    try {
      emitWorkspaceOutput(toWorkspaceOutput(serverOutput));
    } catch (error) {
      console.warn('Discarding malformed Calyx workspace output', error);
    }
  }
}

export async function askCalyx(req: CalyxRequest): Promise<CalyxResponse> {
  const conversationId = await conversationForSession();
  const contextualQuestion = [
    interactionContextText(req.concept),
    'Use canonical Orchid Continuum evidence and explicitly distinguish evidence, inference, missing evidence, and design suggestions.',
    req.question,
  ].join('\n');
  const turn = await sendCalyxTurn(conversationId, {
    message: contextualQuestion,
    project_id: 'illustrated-orchid-lexicon',
    context: calyxContextPacket({
      ...req.context,
      surface: 'illustrated-orchid-lexicon',
      concept: req.concept,
    }),
    research_mode: 'auto',
    retrieval_limit: 12,
  });
  emitTurnWorkspaceOutputs(turn.workspace_outputs);
  const mission = turn.research?.mission ?? null;
  const uncertaintyParts: string[] = [];
  if (mission?.missing_evidence?.length) uncertaintyParts.push(`Evidence gaps: ${mission.missing_evidence.join('; ')}`);
  if (turn.research?.mission_error) uncertaintyParts.push(`Mission limitation: ${turn.research.mission_error}`);
  uncertaintyParts.push('This conversational reply is not automatically published knowledge.');
  return {
    concept: req.concept,
    question: req.question,
    concise_answer: turn.answer,
    uncertainty: uncertaintyParts.join(' '),
    citations: citationsFromMission(mission),
    confidence_or_review_state: mission ? `${mission.review_status || mission.state}${mission.confidence === null ? '' : ` · confidence ${mission.confidence.toFixed(2)}`}` : 'Conversational response; inspect governed evidence where available.',
    mission,
    provider: turn.provider?.name,
    provider_model: turn.provider?.model,
  };
}

export function calyxSuggestedQuestions(conceptLabel: string): string[] {
  return [
    `Why is ${conceptLabel} biologically important?`,
    `Show me how ${conceptLabel} connects to orchid identification characters.`,
    `What visual evidence would help me understand ${conceptLabel}?`,
    `What remains uncertain about ${conceptLabel}?`,
    `Tell me something surprising about ${conceptLabel}.`,
  ];
}

export const CALYX_DEMO_QUESTIONS = [
  'What is this structure or process?',
  'What evidence supports this explanation?',
  'What remains uncertain?',
  'How is this useful for orchid identification?',
  'How does this connect to Calyx Vision?',
];
