import React, { useMemo, useState } from 'react';
import { LexiconEntry } from '@/data/types';
import { computeStats, getCategories } from '@/lib/lexiconService';
import { IMAGERY, integrations, phases, PUBLIC_ACCESS_STATEMENT } from '@/data/partners';
import { SearchField } from './LexiconBrowser';
import { PlateGallery } from './EntryPlate';
import { ResupinationSequence } from './Schematics';
import { SectionHeading } from './ui';
import type { ViewKey } from './SiteChrome';

export const HomeView: React.FC<{ entries: LexiconEntry[]; onOpen: (slug:string)=>void; onNavigate:(view:ViewKey,slug?:string)=>void; onSearch:(q:string)=>void }> = ({ entries,onOpen,onNavigate,onSearch }) => {
  const [query,setQuery]=useState('');
  const stats=useMemo(()=>computeStats(entries),[entries]);
  const categories=useMemo(()=>getCategories(entries),[entries]);
  const featured=useMemo(()=>{const preferred=['resupination','labellum','column','pollinium','velamen','mycorrhiza'];const result=preferred.map((slug)=>entries.find((e)=>e.slug===slug)).filter((e):e is LexiconEntry=>Boolean(e));return result.length?result:entries.slice(0,6);},[entries]);
  return <>
    <section className="relative overflow-hidden bg-[#241534] text-white"><img src={IMAGERY.orchidHero} alt="" aria-hidden className="absolute inset-0 h-full w-full object-cover opacity-20 mix-blend-luminosity"/><div className="absolute inset-0 bg-gradient-to-r from-[#241534] via-[#241534]/95 to-[#241534]/55"/><div className="relative mx-auto grid max-w-7xl gap-10 px-4 py-16 sm:px-6 lg:grid-cols-[1.15fr,.85fr] lg:px-8 lg:py-24"><div><p className="text-[11px] font-semibold uppercase tracking-[0.22em] text-[#A9D8B9]">Orchid Continuum · Famous AI build preserved</p><h1 className="mt-4 max-w-4xl font-serif text-4xl leading-[1.05] text-[#F7F1E4] sm:text-6xl" style={{fontFamily:'Georgia, serif'}}>The Illustrated Orchid Lexicon</h1><p className="mt-5 max-w-2xl text-[17px] leading-relaxed text-[#E7DFF1]">A visual, evidence-aware botanical reference where a term is not merely a definition: it can connect anatomy, development, etymology, literature, figures, taxa, character states, conservation guidance, Vision and Calyx.</p><div className="mt-7 max-w-2xl rounded-sm bg-white p-2 text-stone-900 shadow-2xl"><SearchField value={query} onChange={setQuery} id="lexicon-home-search" large/><button type="button" onClick={()=>onSearch(query)} className="mt-2 w-full rounded-sm bg-[#6B3FA0] px-5 py-3 text-sm font-semibold text-white hover:bg-[#57318A]">Search the lexicon</button></div><p className="mt-4 text-sm text-[#CFC3DA]">{PUBLIC_ACCESS_STATEMENT}</p></div><div className="self-end rounded-sm border border-white/15 bg-white/10 p-6 backdrop-blur-sm"><p className="text-[11px] font-semibold uppercase tracking-[0.18em] text-[#A9D8B9]">Current indexed corpus</p><dl className="mt-4 grid grid-cols-2 gap-4"><div><dt className="text-xs text-[#CFC3DA]">Terms available</dt><dd className="mt-1 font-serif text-4xl text-white">{stats.total_entries}</dd></div><div><dt className="text-xs text-[#CFC3DA]">Categories</dt><dd className="mt-1 font-serif text-4xl text-white">{stats.categories}</dd></div><div><dt className="text-xs text-[#CFC3DA]">Canonical/enriched</dt><dd className="mt-1 font-serif text-4xl text-white">{stats.enriched_entries}</dd></div><div><dt className="text-xs text-[#CFC3DA]">Reviewed</dt><dd className="mt-1 font-serif text-4xl text-white">{stats.expert_reviewed_entries}</dd></div></dl><button type="button" onClick={()=>onNavigate('lexicon')} className="mt-6 text-sm font-semibold text-[#E1C8FA] underline underline-offset-4">Browse all terms →</button></div></div></section>
    <section className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8"><SectionHeading eyebrow="Structured reference" title="A lexicon that grows in layers" lead="The Famous AI build is retained as the presentation layer. Canonical Orchid Continuum records now supersede migration fallback records by concept slug, while absent scientific layers stay visibly absent rather than being fabricated."/><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{['Definition & terminology','Illustration & morphology','Evidence & provenance','Calyx & Vision'].map((title,index)=><article key={title} className="rounded-sm border border-stone-200 bg-white p-5"><p className="text-[10px] font-semibold uppercase tracking-[0.16em] text-[#4A7C59]">Layer {index+1}</p><h3 className="mt-2 font-serif text-xl text-stone-900" style={{fontFamily:'Georgia, serif'}}>{title}</h3><p className="mt-2 text-sm leading-relaxed text-stone-600">{index===0?'Preferred labels, synonyms, scope, definitions, word roots and Botanical Latin.':index===1?'Reusable plates, conceptual schematics, image regions, character states and measurement constraints.':index===2?'Literature, review state, provenance, uncertainty and knowledge relationships.':'Persistent governed conversation, Brain missions and Vision-Lexicon interpretation.'}</p></article>)}</div></section>
    <section className="border-y border-stone-200 bg-[#F6F2EA]"><div className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8"><div className="flex flex-wrap items-end justify-between gap-5"><SectionHeading eyebrow="Featured concepts" title="From the illustrated collection" lead="Richer records occupy more visual space; basic imported records remain deliberately modest."/><button type="button" onClick={()=>onNavigate('collection')} className="rounded-full border border-stone-400 px-5 py-2 text-sm font-medium text-stone-800 hover:bg-white">Open illustrated collection</button></div><div className="mt-8"><PlateGallery entries={featured} onOpen={onOpen}/></div></div></section>
    <section className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8"><SectionHeading eyebrow="Featured morphology" title="Resupination as a visual concept" lead="The original Famous interactive sequence is preserved as an explicitly conceptual schematic, not a measured specimen record."/><div className="mt-8 rounded-sm border border-stone-200 bg-white p-5 sm:p-7"><ResupinationSequence/></div><button type="button" onClick={()=>onOpen('resupination')} className="mt-5 text-sm font-semibold text-[#6B3FA0] underline underline-offset-4">Open the full Resupination entry →</button></section>
    <section className="border-y border-stone-200 bg-white"><div className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8"><SectionHeading eyebrow="Integration" title="One lexicon surface, many canonical systems"/><div className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{integrations.map((item)=><article key={item.name} className="rounded-sm border border-stone-200 bg-[#FDFBF6] p-4"><div className="flex items-center justify-between gap-3"><h3 className="font-medium text-stone-900">{item.name}</h3><span className={`rounded-full px-2 py-0.5 text-[10px] uppercase tracking-wide ${item.status==='connected'?'bg-[#4A7C59]/10 text-[#2F5A3D]':'bg-amber-50 text-amber-800'}`}>{item.status.replaceAll('_',' ')}</span></div><p className="mt-2 text-sm leading-relaxed text-stone-600">{item.description}</p></article>)}</div></div></section>
    <section className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8"><SectionHeading eyebrow="Development record" title="The Famous roadmap, updated for the canonical Continuum"/><div className="mt-7 grid gap-5 md:grid-cols-2">{phases.map((phase)=><article key={phase.id} className="rounded-sm border border-stone-200 bg-white p-5"><p className="text-[10px] font-semibold uppercase tracking-[.14em] text-[#4A7C59]">{phase.statusLabel}</p><h3 className="mt-2 font-serif text-xl text-stone-900" style={{fontFamily:'Georgia, serif'}}>{phase.label}</h3><p className="mt-2 text-sm leading-relaxed text-stone-600">{phase.summary}</p><ul className="mt-3 space-y-1 text-sm text-stone-700">{phase.deliverables.map((d)=><li key={d}>• {d}</li>)}</ul></article>)}</div><p className="mt-6 text-sm text-stone-500">Categories currently represented: {categories.join(' · ')}</p></section>
  </>;
};
