import React, { useMemo, useState } from 'react';
import { LexiconEntry, MaturityFlag } from '@/data/types';
import { ALPHABET, computeStats, getCategories, groupByLetter } from '@/lib/lexiconService';
import { CAPABILITY_MEANING, CapabilityKey, computeCorpusStats, conceptCapabilities, hasIdentificationRelevance } from '@/data/capabilities';
import { EntryPlate } from './EntryPlate';
import { MATURITY_LABELS, MATURITY_ORDER, SectionHeading } from './ui';

type FocusKey = CapabilityKey | 'identification';
const FOCUS_OPTIONS:{key:FocusKey;label:string;hint:string}[]=[
  {key:'illustrated',label:'Illustrated',hint:CAPABILITY_MEANING.illustrated},
  {key:'enriched',label:'Scientifically enriched',hint:CAPABILITY_MEANING.enriched},
  {key:'identification',label:'Used in identification',hint:'Records carrying character states, diagnostic significance or identification cautions.'},
  {key:'conservation_ready',label:'Conservation-ready',hint:CAPABILITY_MEANING.conservation_ready},
  {key:'evidence_linked',label:'Evidence-linked',hint:CAPABILITY_MEANING.evidence_linked},
  {key:'reviewed',label:'Reviewed',hint:CAPABILITY_MEANING.reviewed},
  {key:'published',label:'Published',hint:CAPABILITY_MEANING.published},
];

export const SearchField:React.FC<{value:string;onChange:(v:string)=>void;id?:string;placeholder?:string;large?:boolean}>=({value,onChange,id='lexicon-search',placeholder='Search terms, definitions, synonyms…',large})=><div className="relative"><label htmlFor={id} className="sr-only">Search the lexicon</label><svg aria-hidden viewBox="0 0 20 20" className={`pointer-events-none absolute left-3 ${large?'top-4':'top-3'} h-5 w-5 text-stone-400`} fill="none" stroke="currentColor" strokeWidth="1.6"><circle cx="8.5" cy="8.5" r="5.5"/><path d="M13 13l4 4" strokeLinecap="round"/></svg><input id={id} type="search" value={value} onChange={(e)=>onChange(e.target.value)} placeholder={placeholder} className={`w-full rounded-sm border border-stone-300 bg-white pl-11 pr-4 text-stone-900 placeholder:text-stone-400 focus:border-[#6B3FA0] focus:outline-none focus-visible:ring-2 focus-visible:ring-[#6B3FA0]/40 ${large?'py-4 text-base':'py-2.5 text-sm'}`}/></div>;

export const LexiconBrowser:React.FC<{entries:LexiconEntry[];onOpen:(slug:string)=>void;initialQuery?:string}>=({entries,onOpen,initialQuery=''})=>{
  const[query,setQuery]=useState(initialQuery);const[category,setCategory]=useState('All');const[letter,setLetter]=useState('All');const[maturity,setMaturity]=useState<MaturityFlag|'All'>('All');const[focus,setFocus]=useState<FocusKey|'All'>('All');const[visibleLetters,setVisibleLetters]=useState(8);
  const categories=useMemo(()=>getCategories(entries),[entries]);const stats=useMemo(()=>computeStats(entries),[entries]);const corpus=useMemo(()=>computeCorpusStats(entries),[entries]);
  const focusCounts=useMemo(()=>{const counts:Record<string,number>={identification:corpus.with_identification};FOCUS_OPTIONS.forEach((o)=>{if(o.key!=='identification')counts[o.key]=corpus.capability[o.key as CapabilityKey];});return counts;},[corpus]);
  const filtered=useMemo(()=>{const needle=query.trim().toLowerCase();return entries.filter((e)=>{if(category!=='All'&&e.category!==category)return false;if(letter!=='All'&&e.preferred_term[0]?.toUpperCase()!==letter)return false;if(maturity!=='All'&&!(e.maturity??[]).includes(maturity))return false;if(focus!=='All'){const ok=focus==='identification'?hasIdentificationRelevance(e):conceptCapabilities(e).includes(focus);if(!ok)return false;}if(!needle)return true;return[e.preferred_term,e.quick_definition??'',e.category??'',...(e.synonyms??[]),...(e.related_terminology??[])].join(' ').toLowerCase().includes(needle);});},[entries,query,category,letter,maturity,focus]);
  const grouped=useMemo(()=>groupByLetter(filtered),[filtered]);const activeLetters=useMemo(()=>new Set(entries.map((e)=>e.preferred_term[0]?.toUpperCase()).filter(Boolean)),[entries]);
  const reset=()=>{setQuery('');setCategory('All');setLetter('All');setMaturity('All');setFocus('All');};
  return <div className="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8"><SectionHeading eyebrow="Browse" title="A–Z Lexicon" lead={`Every term is a structured record. ${stats.total_entries} terms are currently indexed across ${stats.categories} categories, of which ${corpus.capability.defined} carry a definition and ${corpus.capability.illustrated} carry a figure.`}/>
    <div className="mt-8 space-y-5 rounded-sm border border-stone-200 bg-white p-5"><div className="grid gap-4 md:grid-cols-[2fr,1fr,1fr]"><SearchField value={query} onChange={setQuery}/><div><label htmlFor="cat-filter" className="mb-1 block text-xs font-medium text-stone-600">Category</label><select id="cat-filter" value={category} onChange={(e)=>setCategory(e.target.value)} className="w-full rounded-sm border border-stone-300 bg-white px-3 py-2.5 text-sm text-stone-900"><option value="All">All categories</option>{categories.map((c)=><option key={c} value={c}>{c}</option>)}</select></div><div><label htmlFor="mat-filter" className="mb-1 block text-xs font-medium text-stone-600">Development state</label><select id="mat-filter" value={maturity} onChange={(e)=>setMaturity(e.target.value as MaturityFlag|'All')} className="w-full rounded-sm border border-stone-300 bg-white px-3 py-2.5 text-sm text-stone-900"><option value="All">Any state</option>{MATURITY_ORDER.map((m)=><option key={m} value={m}>{MATURITY_LABELS[m]}</option>)}</select></div></div>
    <div><p id="focus-label" className="mb-2 text-xs font-medium text-stone-600">What the record carries</p><div className="flex flex-wrap gap-2" role="group" aria-labelledby="focus-label"><button type="button" onClick={()=>setFocus('All')} aria-pressed={focus==='All'} className={`rounded-full border px-3 py-1.5 text-[12px] font-medium ${focus==='All'?'border-[#6B3FA0] bg-[#6B3FA0] text-white':'border-stone-300 bg-white text-stone-700'}`}>Any capability</button>{FOCUS_OPTIONS.map((o)=><button key={o.key} type="button" title={o.hint} onClick={()=>setFocus(focus===o.key?'All':o.key)} aria-pressed={focus===o.key} className={`rounded-full border px-3 py-1.5 text-[12px] font-medium ${focus===o.key?'border-[#4A7C59] bg-[#4A7C59] text-white':'border-stone-300 bg-white text-stone-700'}`}>{o.label} <span className={focus===o.key?'text-white/80':'text-stone-500'}>({focusCounts[o.key]??0})</span></button>)}</div>{focus!=='All'&&<p className="mt-2 max-w-3xl text-[12px] leading-relaxed text-stone-500">{FOCUS_OPTIONS.find((o)=>o.key===focus)?.hint}</p>}</div>
    <div><p id="letter-label" className="mb-2 text-xs font-medium text-stone-600">Jump to letter</p><div className="flex flex-wrap gap-1" role="group" aria-labelledby="letter-label"><button type="button" onClick={()=>setLetter('All')} aria-pressed={letter==='All'} className={`rounded-sm border px-2.5 py-1 text-xs font-medium ${letter==='All'?'border-[#6B3FA0] bg-[#6B3FA0] text-white':'border-stone-300 bg-white text-stone-700'}`}>All</button>{ALPHABET.map((l)=>{const has=activeLetters.has(l);return <button key={l} type="button" disabled={!has} onClick={()=>setLetter(l)} aria-pressed={letter===l} className={`h-7 w-7 rounded-sm border text-xs font-medium ${letter===l?'border-[#6B3FA0] bg-[#6B3FA0] text-white':has?'border-stone-300 bg-white text-stone-700':'cursor-not-allowed border-stone-200 bg-stone-50 text-stone-300'}`}>{l}</button>;})}</div></div>
    <div className="flex flex-wrap items-center justify-between gap-3 border-t border-stone-100 pt-4"><p role="status" className="text-sm text-stone-600">Showing <strong className="text-stone-900">{filtered.length}</strong> of {entries.length} indexed terms</p><button type="button" onClick={reset} className="rounded-sm border border-stone-300 px-3 py-1.5 text-xs font-medium text-stone-700 hover:bg-stone-100">Clear all filters</button></div></div>
    {filtered.length===0?<p className="mt-10 rounded-sm border border-dashed border-stone-300 bg-white p-10 text-center text-stone-600">No indexed term matches those criteria. The lexicon is growing as structured records are prepared and reviewed.</p>:<div className="mt-12 space-y-16">{Object.keys(grouped).sort().slice(0,visibleLetters).map((l)=><section key={l} aria-labelledby={`letter-${l}`}><div className="mb-6 flex items-baseline gap-5"><h3 id={`letter-${l}`} className="font-serif text-[3.2rem] leading-none text-[#6B3FA0]/70" style={{fontFamily:'Georgia, serif'}}>{l}</h3><span aria-hidden className="mb-3 flex-1 border-t border-stone-300"/><span className="text-xs uppercase tracking-[0.14em] text-stone-500">{grouped[l].length} {grouped[l].length===1?'term':'terms'}</span></div><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{grouped[l].map((e)=><EntryPlate key={e.slug} entry={e} onOpen={onOpen}/>)}</div></section>)}{Object.keys(grouped).length>visibleLetters&&<div className="text-center"><button type="button" onClick={()=>setVisibleLetters((n)=>n+6)} className="rounded-full border border-stone-400 px-6 py-2.5 text-[14px] font-medium text-stone-800 hover:bg-white">Show more letters ({Object.keys(grouped).length-visibleLetters} remaining)</button></div>}</div>}
  </div>;
};
