import React, { useState } from 'react';
import { AI_TRANSPARENCY_STATEMENT, BRAND, DEMO_BANNER, NHOS_WEBSITE, PUBLIC_ACCESS_STATEMENT } from '@/data/partners';
import { DisplaySettings, ThemeQuickToggle } from './DisplaySettings';

export type ViewKey = 'home' | 'lexicon' | 'collection' | 'entry' | 'partners' | 'about' | 'admin' | 'validation';

export const DemoBanner: React.FC = () => <div className="bg-[#3E2A55] px-4 py-2 text-center text-[12px] leading-snug text-[#EFE7F7]"><span className="mx-auto inline-flex max-w-4xl items-center justify-center gap-2"><svg aria-hidden viewBox="0 0 12 12" className="h-2 w-2 flex-none" fill="currentColor"><circle cx="6" cy="6" r="5" /></svg>{DEMO_BANNER}</span></div>;

export const SiteHeader: React.FC<{ view: ViewKey; onNavigate: (v: ViewKey, slug?: string) => void }> = ({ view, onNavigate }) => {
  const [open, setOpen] = useState(false);
  const nav: { key: ViewKey; label: string }[] = [
    { key: 'home', label: 'Home' }, { key: 'lexicon', label: 'A–Z Lexicon' }, { key: 'collection', label: 'Illustrated Collection' }, { key: 'validation', label: 'Illustration Validation' }, { key: 'about', label: 'Project & Provenance' }, { key: 'partners', label: 'Partners & Supporters' },
  ];
  return <header className="sticky top-0 z-40 border-b border-white/10 bg-[#241534] shadow-[0_10px_30px_-24px_rgba(0,0,0,0.8)]">
    <div className="mx-auto flex max-w-7xl items-center justify-between gap-4 px-4 py-3 sm:px-6 lg:px-8">
      <button type="button" onClick={() => onNavigate('home')} className="flex items-center gap-3 rounded-sm text-left focus:outline-none focus-visible:ring-2 focus-visible:ring-[#D8B7F5]"><span className="relative flex-none"><span aria-hidden className="absolute -inset-1.5 rounded-full bg-[#D8B7F5]/20 blur-md" /><img src={BRAND.orchidContinuum} alt="Orchid Continuum — The Global Orchid Experience" className="relative h-11 w-11 flex-none object-contain sm:h-14 sm:w-14" /></span><span className="min-w-0"><span className="block text-[10px] font-semibold uppercase tracking-[0.2em] text-[#A9D8B9]">Orchid Continuum</span><span className="block truncate font-serif text-lg leading-tight text-[#F7F1E4] sm:text-xl" style={{ fontFamily: 'Georgia, serif' }}>Illustrated Orchid Lexicon</span></span></button>
      <nav aria-label="Primary" className="hidden items-center gap-0.5 lg:flex">{nav.map((n) => <button key={n.key} type="button" onClick={() => onNavigate(n.key)} aria-current={view === n.key ? 'page' : undefined} className={`relative rounded-full px-3 py-2 text-[13px] transition-colors focus:outline-none focus-visible:ring-2 focus-visible:ring-[#D8B7F5] ${view === n.key ? 'bg-white/15 font-semibold text-white' : 'text-[#E7DFF1] hover:bg-white/10 hover:text-white'}`}>{n.label}{view === n.key && <span aria-hidden className="absolute inset-x-3 -bottom-0.5 h-0.5 rounded-full bg-[#D8B7F5]" />}</button>)}</nav>
      <div className="flex items-center gap-2"><button type="button" onClick={() => onNavigate('entry', 'resupination')} className="hidden rounded-full bg-[#D8B7F5] px-4 py-2 text-[13px] font-semibold text-[#33184F] transition-transform hover:scale-[1.03] focus:outline-none focus-visible:ring-2 focus-visible:ring-white md:inline-flex">Featured: Resupination</button><ThemeQuickToggle /><DisplaySettings /><button type="button" onClick={() => setOpen((o) => !o)} aria-expanded={open} aria-controls="lexicon-mobile-nav" className="inline-flex h-9 w-9 items-center justify-center rounded-full border border-white/25 bg-white/10 text-[#F3EEE2] lg:hidden focus:outline-none focus-visible:ring-2 focus-visible:ring-[#D8B7F5]"><span className="sr-only">Toggle navigation</span><svg viewBox="0 0 20 20" className="h-5 w-5" fill="none" stroke="currentColor" strokeWidth="1.6"><path d="M3 6h14M3 10h14M3 14h14" strokeLinecap="round" /></svg></button></div>
    </div>
    <div id="lexicon-mobile-nav" hidden={!open} className="border-t border-white/10 bg-[#241534] lg:hidden"><nav aria-label="Primary mobile" className="mx-auto max-w-7xl px-4 py-2">{[...nav, { key: 'entry' as ViewKey, label: 'Featured: Resupination' }].map((n) => <button key={n.label} type="button" onClick={() => { setOpen(false); onNavigate(n.key, n.key === 'entry' ? 'resupination' : undefined); }} className="block w-full border-b border-white/10 px-2 py-3.5 text-left text-[15px] text-[#EFE7F7] last:border-b-0">{n.label}</button>)}</nav></div>
  </header>;
};

export const AITransparency: React.FC<{ compact?: boolean }> = ({ compact }) => <aside aria-label="AI transparency statement" className={`rounded-sm border border-stone-200 bg-white/70 ${compact ? 'p-4' : 'p-5'}`}><h2 className="text-[11px] font-semibold uppercase tracking-[0.16em] text-[#4A7C59]">AI transparency</h2><p className="mt-2 text-[13px] leading-relaxed text-stone-600">{AI_TRANSPARENCY_STATEMENT}</p><p className="mt-2 text-[13px] leading-relaxed text-stone-600">Every visual asset is labelled by kind and retains provenance so a teaching diagram is never silently presented as a documentary specimen image.</p></aside>;

export const SignupForm: React.FC = () => {
  const [email, setEmail] = useState('');
  const [message, setMessage] = useState('');
  return <form onSubmit={(e) => { e.preventDefault(); setMessage('Newsletter signup is being migrated from the Famous prototype into the canonical Orchid Continuum communications workflow.'); }} className="space-y-3"><label htmlFor="lexicon-signup" className="block text-xs font-medium text-stone-600">Email address</label><input id="lexicon-signup" type="email" required value={email} onChange={(e) => setEmail(e.target.value)} className="w-full rounded-sm border border-stone-300 bg-white px-3 py-2 text-sm text-stone-900 focus:border-[#6B3FA0] focus:outline-none focus-visible:ring-2 focus-visible:ring-[#6B3FA0]/40" /><button type="submit" className="w-full rounded-sm bg-[#4A7C59] px-4 py-2.5 text-sm font-medium text-white hover:bg-[#3C6549]">Follow the lexicon’s development</button>{message && <p role="status" className="text-[12px] leading-relaxed text-stone-600">{message}</p>}</form>;
};

export const SiteFooter: React.FC<{ onNavigate: (v: ViewKey, slug?: string) => void }> = ({ onNavigate }) => <footer className="mt-20 border-t border-stone-200 bg-[#F6F2EA]"><div className="mx-auto max-w-7xl px-4 py-14 sm:px-6 lg:px-8"><div className="grid gap-10 lg:grid-cols-4"><div className="lg:col-span-2"><div className="flex items-start gap-3"><img src={BRAND.orchidContinuum} alt="Orchid Continuum logo" className="h-16 w-16 flex-none object-contain" /><div><p className="font-serif text-lg text-stone-900" style={{ fontFamily: 'Georgia, serif' }}>The Illustrated Orchid Lexicon</p><p className="text-sm text-stone-600">A resource of the Orchid Continuum</p></div></div><p className="mt-5 max-w-xl text-[15px] leading-relaxed text-stone-700">{PUBLIC_ACCESS_STATEMENT}</p><p className="mt-4 max-w-xl text-[13px] leading-relaxed text-stone-500">This interface preserves the Famous AI build while its data authority is migrated into the canonical Concept Registry, Literature, Vision, Knowledge Graph and Calyx services.</p></div><nav aria-label="Footer" className="text-sm"><h2 className="text-[11px] font-semibold uppercase tracking-[0.16em] text-[#4A7C59]">Explore</h2><ul className="mt-3 space-y-2">{[{ label:'A–Z Lexicon', view:'lexicon' as ViewKey },{ label:'Illustrated Collection',view:'collection' as ViewKey },{ label:'Featured: Resupination',view:'entry' as ViewKey,slug:'resupination' },{ label:'Illustration validation',view:'validation' as ViewKey },{ label:'Project & provenance',view:'about' as ViewKey },{ label:'Partners & supporters',view:'partners' as ViewKey }].map((l)=><li key={l.label}><button type="button" onClick={()=>onNavigate(l.view,l.slug)} className="text-left text-stone-700 underline decoration-stone-300 underline-offset-2 hover:text-[#6B3FA0]">{l.label}</button></li>)}<li><a href={NHOS_WEBSITE} target="_blank" rel="noopener noreferrer" className="text-stone-700 underline decoration-stone-300 underline-offset-2 hover:text-[#6B3FA0]">New Hampshire Orchid Society</a></li></ul></nav><div><h2 className="text-[11px] font-semibold uppercase tracking-[0.16em] text-[#4A7C59]">Project updates</h2><p className="mt-3 text-[13px] leading-relaxed text-stone-600">Receive notice as glossary entries, illustrations and provenance records are published.</p><div className="mt-4"><SignupForm /></div></div></div><div className="mt-12 border-t border-stone-300 pt-8"><AITransparency compact /><p className="mt-6 text-xs text-stone-500">© {new Date().getFullYear()} Orchid Continuum · Famous AI Illustrated Orchid Lexicon migrated into the canonical Orchid Continuum.</p></div></div></footer>;
